name: workflow principal
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ::notice::un message info
          echo ::warning::un message warning
          echo ::error::un message error
